apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: infra-gitops
spec:
  components:
  - name: database-config
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/wonderflow/ocm-kubevela-demo
      secretRef: git-secret
      pullInterval: 10m
      git:
        branch: gitops
      path: ./infrastructure
