apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
spec:
  components:
    - name: my-server
      type: webservice
      properties:
        image: oamdev/ocm-vela-demo:master-9d96c470-1636327907 # {"$imagepolicy": "default:app-gitops"}
        port: 9080
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: dev-db-conn
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: dev-db-conn
                key: DB_USER
      traits:
        - type: ingress
          properties:
            domain: dev.c76af67709f3d464d8389355256c2368a.cn-hangzhou.alicontainer.com
            http:
              /: 9080
  policies:
    - name: health-policy-demo
      type: health
      properties:
        probeInterval: 30
        probeTimeout: 60
    - name: multi-env-policy
      type: env-binding
      properties:
        envs:
          - name: dev
            placement:
              clusterSelector:
                name: vela-dev
            selector:
              components:
                - my-server
          - name: prod
            placement:
              clusterSelector:
                name: vela-prod
            patch:
              components:
                - name: my-server
                  type: webservice
                  traits:
                    - type: ingress
                      properties:
                        domain: prod.c78a0f953105342f2a22ee3f4bb6835a7.cn-hangzhou.alicontainer.com
  workflow:
    steps:
      - name: deploy-dev
        type: deploy2env
        properties:
          policy: multi-env-policy
          env: dev
      - name: dev-notification
        type: webhook-notification
        properties:
          slack:
            url:
              fromSecret:
                name: my-secret
                key: slack
            message:
              text: "Successfully apply the app in dev cluster."
      - name: manual-approval
        type: suspend
      - name: deploy-prod
        type: deploy2env
        properties:
          policy: multi-env-policy
          env: prod
      - name: prod-notification
        type: webhook-notification
        properties:
          slack:
            url:
              fromSecret:
                name: my-secret
                key: slack
            message:
              text: "Successfully apply the app in prod cluster."
