apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-dev-rds
  annotations:
    db: dev-only
spec:
  components:
    - name: dev-db
      type: alibaba-rds
      properties:
        instance_name: dev-db
        account_name: dev
        password: my-password
        writeConnectionSecretToRef:
          name: dev-db-conn
  workflow:
    steps:
      - name: deploy-dev-db
        type: apply-component
        properties:
          component: dev-db
      - name: dev-notification
        type: webhook-notification
        properties:
          slack:
            url:
              fromSecret:
                name: my-secret
                key: slack
            message:
              text: "Successfully apply the database in dev cluster."
      - name: read-dev-secret
        type: read-object
        outputs:
          - name: dev-secret-value
            valueFrom: output.value.data
        properties:
          apiVersion: v1
          kind: Secret
          name: dev-db-conn
      - name: apply-dev-secret
        type: apply-object
        inputs:
          - from: dev-secret-value
            parameterKey: value.data
        properties:
          value:
            apiVersion: v1
            kind: Secret
            metadata:
              name: dev-db-conn
          cluster: dev
