apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-dev-rds
  annotations:
    db: dev-only
spec:
  components:
    - name: dev-db
      type: alibaba-rds
      properties:
        instance_name: dev-db
        account_name: dev
        password: my-password
        writeConnectionSecretToRef:
          name: dev-db-conn
  workflow:
    steps:
      - name: deploy-dev-db
        type: apply-component
        properties:
          component: dev-db
      - name: dev-notification
        type: webhook-notification
        properties:
          slack:
            url:
              fromSecret:
                name: my-secret
                key: slack
            message:
              text: "Successfully apply the database in dev cluster."
