apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-prod-rds
spec:
  components:
    - name: prod-db
      type: alibaba-rds
      properties:
        instance_name: prod-db
        account_name: prod
        password: my-password
        writeConnectionSecretToRef:
          name: prod-db-conn

  workflow:
    steps:
      - name: deploy-prod-db
        type: apply-component
        properties:
          component: prod-db
      - name: prod-notification
        type: webhook-notification
        properties:
          slack:
            url:
              fromSecret:
                name: my-secret
                key: slack
            message:
              text: "Successfully apply the database in prod cluster."
      - name: read-prod-secret
        type: read-object
        outputs:
          - name: prod-secret-value
            valueFrom: output.value.data
        properties:
          apiVersion: v1
          kind: Secret
          name: prod-db-conn
      - name: apply-prod-secret
        type: apply-object
        inputs:
          - from: prod-secret-value
            parameterKey: value.data
        properties:
          value:
            apiVersion: v1
            kind: Secret
            metadata:
              name: dev-db-conn
          cluster: vela-prod
